# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll
image: ruby:latest

cache:
  key: "global"
  paths:
    - vendor/bundle

before_script:
  - gem install bundler
  - bundle install --path vendor/bundle

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
    expire_in: 1 week
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  environment: gitlab-pages
  only:
  - master
