language: ruby
python: 
  - "3.5"
cache: bundler
rvm:
  - 2.3.3

script:
  - bash ./script/cibuild

deploy:
  provider: script
  script: bash ./script/rollbar
  on:
    branch: master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
